# Generated by Django 3.1.7 on 2021-03-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_is_first_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagebot',
            name='reply_to_message_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagebot',
            name='last_name',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
