# Generated by Django 3.1.7 on 2021-03-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210317_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBot',
            fields=[
                ('message_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=220)),
                ('chat_id', models.CharField(max_length=220)),
                ('from_id', models.CharField(max_length=220)),
                ('first_name', models.CharField(max_length=220)),
                ('last_name', models.CharField(max_length=220)),
            ],
        ),
    ]
