# Generated by Django 3.1.7 on 2021-03-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20210318_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='context',
        ),
        migrations.RemoveField(
            model_name='response',
            name='context',
        ),
    ]
